#!/usr/bin/env tsx
/**
 * scripts/generate_mcp_docs.ts
 *
 * Lightweight MCP tool doc generator that avoids external parser
 * dependencies. It scans packages/mcp-server/src/index.ts for registered tool
 * names and emits a short markdown summary.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

interface ToolDef {
  name: string;
  description: string;
  sourceLine: number;
}

function main(): void {
  const indexPath = resolve('packages/mcp-server/src/index.ts');
  const outPath = resolve('docs/mcp-tools.md');

  const tools = extractTools(indexPath);
  if (tools.length === 0) {
    console.error(`No tools found in ${indexPath}.`);
    process.exit(1);
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderMarkdown(tools));
  console.log(`wrote ${tools.length} tools to ${outPath}`);
}

function extractTools(indexPath: string): ToolDef[] {
  const text = readFileSync(indexPath, 'utf8');
  const toolNames = new Set<string>();
  const pattern = /name:\s*'([^']+)'/g;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(text))) {
    toolNames.add(match[1]);
  }

  return [...toolNames].map((name, index) => ({
    name,
    description: `MCP tool: ${name}`,
    sourceLine: index + 1,
  }));
}

function renderMarkdown(tools: ToolDef[]): string {
  const lines: string[] = [];
  lines.push('# MCP Tools Reference');
  lines.push('');
  lines.push('<!-- AUTO-GENERATED by scripts/generate_mcp_docs.ts -->');
  lines.push('');
  lines.push(`Detected ${tools.length} tools from \`packages/mcp-server/src/index.ts\`.`);
  lines.push('');

  const groups = new Map<string, ToolDef[]>();
  for (const tool of tools) {
    const prefix = tool.name.split('_')[0] ?? 'misc';
    const list = groups.get(prefix) ?? [];
    list.push(tool);
    groups.set(prefix, list);
  }

  for (const [group, items] of [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`## ${group}`);
    lines.push('');
    for (const tool of items) {
      lines.push(`- \`${tool.name}\` - ${tool.description} (line ${tool.sourceLine})`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

main();